config/routes.rb
Storybook::Application.routes.draw do
  resources :schools
  resources :classrooms do
    resources :book_bags, only: [:new, :index]
    resources :plans, only: [:new, :index]
    resources :students, only: [:new]
    resources :inventory_states, only: [:new]
  end
  resources :inventory_states, only: [:create, :show, :destroy]
  resources :assignments, only: [:update]
  resources :book_bags, except: [:new]
  resources :students, except: [:new]
  resources :plans, except: [:new, :index]

  root 'home#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :school
  has_many :students, dependent: :destroy
  has_many :book_bags, dependent: :destroy
  has_many :assignments, -> { joins(:student) }, through: :plans
  has_many :returned_assignments, -> { joins(:book_bag) }, through: :inventory_states, source: :assignments

  has_many :periods
  has_many :inventory_states, through: :periods
  has_many :plans, through: :periods, dependent: :destroy

  # All assignments that are out on loan
  # This can likely be rewritten in SQL
  def loaned_assignments
    assignments - returned_assignments
  end

  def available_book_bags
    book_bags.active - loaned_assignments.map(&:book_bag)
  end

  def eligible_for_new_plan?
    !!!current_plan.try(:active?)
  end

  def current_plan
    current_period.try(:plan)
  end

  def current_period
    periods.last
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def active_students
    students.name_sorted.active
  end

  def display_plans
    plans.order("id DESC")
  end

  def eligible_students
    active_students - loaned_assignments.map(&:student)
  end

  def presenter
    @presenter ||= ClassroomPresenter.new(self)
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @plans = @classroom.display_plans
    @presenter = ClassroomPresenter.new(@classroom)
    @students = @presenter.students
    @book_bags = @classroom.book_bags
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: "Classroom was successfully created." }
        format.json { render action: "show", status: :created, location: @classroom }
      else
        format.html { render action: "new" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: "Classroom was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_classroom
    @classroom = Classroom.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def classroom_params
    params[:classroom].permit(:name, :school_id)
  end
end

app/views/classrooms/_book_bags.html.haml
%section.book-bags-management
  %h2= "Book bags (#{book_bags.count})"
  = link_to "Add a book bag", new_classroom_book_bag_path(classroom), class: "btn btn-success btn-xs"
  %table.table.table-responsive
    %thead
      %tr
        %th Book Bag ID
        %th{:title => "Is this current bag eligible for rotation in the classroom?"} Active?
    %tbody
      - book_bags.each do |bag|
        %tr{:data => {:book_bag_id => bag.id} }
          %td.book-bag-id= link_to bag.global_id, edit_book_bag_path(bag)
          %td.is-active= bag.active? ? "Y" : "-"

app/views/classrooms/_form.html.haml
= simple_form_for(@classroom, html: {class: "form-horizontal"}) do |f|
  = f.error_notification

  = f.input :name, required: true, class: "form-control"
  = f.input :school_id, collection: School.all, value_method: :id, label_method: :name, required: true
  = f.button :submit, class: "btn-primary"

app/views/classrooms/_out_on_loan.html.haml
%section.out-on-loan
  %h2 Out on loan
  - if classroom.loaned_assignments.blank?
    There are no book bags out on loan for this class.
  - else
    %table.table.table-responsive
      %thead
        %tr
          %th Student
          %th Bag
          %th Since
          %th Periods
      %tbody
        - classroom.loaned_assignments.each do |la|
          %tr{:data => { :"assignment-id" => la.id, :"student-id" => la.student.id }}
            %td.out-on-loan__student
              = la.student.full_name
            %td.out-on-loan__bag
              = la.book_bag.global_id
            %td.out-on-loan__since
              = la.loaned_period.name
            %td.out-on-loan__periods
              = classroom.current_period.periods_from(la.loaned_period)

app/views/classrooms/_plan_matrix.html.haml
%section
  %h2= "Plans"
  = link_to "Create Plan", new_classroom_plan_path(classroom), class: "btn btn-success btn-s", disabled: !classroom.eligible_for_new_plan?
  - if plans.blank?
    %p There are no plans. Might you want to create one?
  - else
    %table.table.table-responsive.plan-matrix
      %thead
        %tr
          %th Name
          - plans.each do |plan|
            %th= plan.presenter.name
      %tbody
        - students.each do |s|
          %tr
            = classroom.presenter.header_cell_for(s) do
              - raw "#{s.full_name} #{classroom.presenter.header_cell_icon(s)}"
            - plans.each do |plan|
              %td{:class => (plan.period.active? ? "bg-success" : "bg-warning")}
                = plan.presenter.display_cell_for(s)
      %tfoot
        %tr
          %td
          - plans.each_with_index do |plan, i|
            %td{"data-actions": true}
              .btn-group
                = link_to "Take Inventory",
                  new_classroom_inventory_state_path(classroom),
                  class: "btn btn-warning btn-s",
                  title: "You must first take inventory of book bags before you may create a new plan.",
                  disabled: !plan.inventoryable?
                %button{class: "btn btn-default btn-s dropdown-toggle",
                        data: { toggle: "dropdown" },
                        "aria-haspopup": true,
                        "aria-expanded": false,
                        type: :button}
                  More
                  %span.caret
                %ul.dropdown-menu.dropdown-menu-right
                  %li{class: (!plan.editable? ? :disabled : nil)}
                    = link_to edit_plan_path(plan) do
                      %i.glyphicon.glyphicon-edit
                      Edit Plan
                  %li.divider{role: :separator}
                  %li{class: (!plan.deletable? ? :disabled : nil)}
                    = link_to plan_path(plan),
                      method: "delete",
                      disabled: !plan.deletable?,
                      data: { confirm: "You are about to delete the plan #{plan.name}. Are you sure? This action is irreversible!"} do
                      %i.glyphicon.glyphicon-trash
                      Delete Plan
                      = plan.deletable? ? "" : " (Disabled)"
                    %li{class: "#{!plan.inventory_state_deletable? ? :disabled : nil}"}
                      = link_to plan.inventory_state_deletable? ? inventory_state_path(plan.inventory_state) : '#',
                        disabled: !plan.inventory_state_deletable?,
                        method: "delete",
                        data: {confirm: "Are you sure you want to delete the inventory?"} do
                        %i.glyphicon.glyphicon-trash
                        Delete Inventory
                        = plan.inventory_state_deletable? ? "" : " (Disabled)"

app/views/classrooms/_students.html.haml
%section.students-management
  %h2= "Students (#{students.count})"
  = link_to "Add a student", new_classroom_student_path(classroom), class: "btn btn-success btn-xs"
  %table.table.table-responsive
    %thead
      %tr
        %th Name
    %tbody
      - students.each do |student|
        %tr
          %td= link_to student.full_name, student_path(student)

app/views/classrooms/edit.html.haml
%h1 Editing classroom

= render 'form'

= link_to 'Show', @classroom
\|
= link_to 'Back', classrooms_path

app/views/classrooms/index.html.haml
%h2 Classrooms

%table.table.table-responsive
  %tr
    %th Name
    %th
    %th
    %th

  - @classrooms.each do |classroom|
    %tr
      %td= classroom.name
      %td= link_to 'Show', classroom
      %td= link_to 'Edit', edit_classroom_path(classroom)
      %td= link_to 'Destroy', classroom, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Classroom', new_classroom_path, class: "btn btn-xs btn-success"

app/views/classrooms/new.html.haml
%h1 New classroom

= render 'form'

= link_to 'Back', classrooms_path

app/views/classrooms/show.html.haml
.row
  .col-xs-10
    %h1= "#{@classroom.name}"
  .col-xs-2
    = link_to 'Edit classroom info', edit_classroom_path(@classroom)

.row
  .col-xs-12
    = render partial: "plan_matrix", locals: { classroom: @classroom, plans: @plans, students: @students }
.row
  .col-md-4
    = render partial: "out_on_loan", locals: { classroom: @classroom }
  .col-md-4
    = render partial: "students", locals: { classroom: @classroom, plans: @plans, students: @students }
  .col-md-4
    = render partial: "book_bags", locals: { classroom: @classroom, plans: @plans, students: @students, book_bags: @book_bags }