config/routes.rb
Storybook::Application.routes.draw do
  resources :schools
  resources :classrooms do
    resources :book_bags, only: [:new, :index]
    resources :plans, only: [:new, :index]
    resources :students, only: [:new]
    resources :inventory_states, only: [:new]
  end
  resources :inventory_states, only: [:create, :show, :destroy]
  resources :assignments, only: [:update]
  resources :book_bags, except: [:new]
  resources :students, except: [:new]
  resources :plans, except: [:new, :index]

  root 'home#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :classroom
  has_many :assignments

  scope :name_sorted, -> { order(:first_name, :last_name) }
  scope :active, -> { where(inactive: false) }

  def full_name
    "#{first_name} #{last_name}"
  end

  # TODO/move me to a aliased method
  def past_assignments
    assignments
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_classroom, only: [:new]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new(classroom: @classroom)
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html do
          redirect_to new_classroom_student_path(@student.classroom),
                      notice: "Student #{@student.full_name} was successfully created."
        end
        format.json { render action: "show", status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  def set_classroom
    @classroom = Classroom.find(params[:classroom_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params[:student].permit(:first_name, :last_name, :classroom_id, :inactive)
  end
end

app/views/students/_form.html.haml
= simple_form_for(@student, html: {class: "form-horizontal"}) do |f|
  = f.error_notification

  = f.input :first_name, required: true
  = f.input :last_name, required: true
  = f.input :classroom_id, collection: Classroom.all, value_method: :id, label_method: :name, required: true
  = f.input :inactive, required: true
  = f.button :submit, class: "btn-primary"

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table.table.table-responsive
  %tr
    %th First
    %th Last
    %th Classroom
    %th
    %th
    %th

  - @students.each do |student|
    %tr
      %td= student.first_name
      %td= student.last_name
      %td= student.classroom.try(:name)
      %td= link_to 'Show', student
      %td= link_to 'Edit', edit_student_path(student)
      %td= link_to 'Destroy', student, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', classroom_path(@classroom)

app/views/students/show.html.haml
%h1= @student.full_name

%dl
  %dt Classroom
  %dd= link_to @student.classroom.name, classroom_path(@student.classroom)
  %dt Inactive?
  %dd= @student.inactive?

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path