config/routes.rb
Storybook::Application.routes.draw do
  resources :schools
  resources :classrooms do
    resources :book_bags, only: [:new, :index]
    resources :plans, only: [:new, :index]
    resources :students, only: [:new]
    resources :inventory_states, only: [:new]
  end
  resources :inventory_states, only: [:create, :show, :destroy]
  resources :assignments, only: [:update]
  resources :book_bags, except: [:new]
  resources :students, except: [:new]
  resources :plans, except: [:new, :index]

  root 'home#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :period, autosave: true, dependent: :destroy
  has_one :classroom, through: :period
  has_many :assignments, -> { joins(:student).order("students.first_name DESC") }, dependent: :destroy
  has_one :inventory_state, through: :period

  accepts_nested_attributes_for :period
  accepts_nested_attributes_for :assignments

  validates :assignments, presence: true

  after_initialize :initialize_period

  delegate :name, to: :period

  def book_bags
    # We can't do a `has_many :book_bags, through: :assignments`
    # because we need this to work on a nonpersisted object
    assignments.map(&:book_bag)
  end

  def ordered_book_bags
    book_bags.sort_by(&:global_id)
  end

  def active?
    inventory_state.nil?
  end
  alias_method :editable?, :active?
  alias_method :deletable?, :active?
  alias_method :inventoryable?, :active?

  def closed?
    inventory_state.present?
  end

  def inventory_state_deletable?
    !!inventory_state.try(:deletable?)
  end

  def presenter
    @presenter ||= PlanPresenter.new(self)
  end

  def initialize_period
    self.period ||= Period.new
  end

  def template
    Hash[assignments.map(&:to_plan_array)]
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :set_classroom, only: [:new, :index]

  rescue_from PlanGenerator::NoPlanFound, with: :no_plan_found

  def no_plan_found(e)
    Rails.logger.info(<<-MSG
                      #{e.message}
                      No plan found.
                      #{e.backtrace.join("\n")}
                      MSG
                     )
    redirect_to classroom_path(@classroom),
                alert: "Unable to generate a new plan for this classroom. Please try adding another bag."
  end

  # GET /plans
  # GET /plans.json
  def index
    @plans = @classroom.plans
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /classrooms/:classroom_id/plans/new
  def new
    @plan = Plan.new classroom: @classroom
    pg = PlanGenerator.new(@classroom.eligible_students, @classroom.available_book_bags)
    assignments = pg.generate
    @plan.assignments += assignments
  end

  # GET /plans/1/edit
  def edit
    @classroom = @plan.classroom
    @out_on_loan_assignments = @classroom.loaned_assignments - @plan.assignments
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to classroom_url(@plan.classroom), notice: "Plan was successfully created." }
        format.json { render action: "show", status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if PlanUpdater.new(@plan, plan_params).update
        format.html { redirect_to @plan.classroom, notice: "Plan was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    classroom = @plan.classroom
    @plan.destroy
    respond_to do |format|
      Rails.logger.info "Classroom: #{classroom.inspect}"
      format.html { redirect_to classroom_url(classroom), notice: "Plan was successfully deleted" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_plan
    @plan = Plan.find(params[:id])
  end

  def set_classroom
    @classroom = Classroom.find(params[:classroom_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def plan_params
    params.require(:plan).permit(
      period_attributes: [:id, :name, :classroom_id],
      assignments_attributes: [:id, :book_bag_id, :student_id]
    )
  end
end

app/views/plans/_form.html.haml
= simple_form_for(@plan, html: { 'js-validate-dedupe': true }) do |f|
  = f.error_notification
  .form-inputs

    = f.simple_fields_for :period do |pf|
      = pf.input :name
      = pf.input :classroom_id, as: :hidden

    .form-group
      %table.table.table-responsive
        %thead
          %tr
            %th Name
            %th{:data => {:extractor => "select-text"}} Book Bag
        %tbody
          = f.simple_fields_for :assignments do |af|
            %tr{:data => {:student_id => af.object.student_id}}
              %td.student-name
                = af.object.student.try(:full_name)
                = af.input :student_id, as: :hidden
              %td
                = af.association :book_bag,
                  collection: @classroom.book_bags.active.by_global_id,
                  label_method: :global_id,
                  label: false,
                  required: true

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/plans/_loaned_assignments.html.haml
%h2 Assignments still out on loan

%table.table.table--loaned-assignments
  %thead
    %tr
      %th Student
      %th Book Bag
      %th Action
  %tbody
    - assignments.each do |a|
      %tr
        %td.column--full-name= a.student.full_name
        %td.column--book-bag-global-id= a.book_bag.global_id
        %td.column--action= link_to 'Process late return', assignment_path(a, plan_id: plan.id), class: 'btn btn-xs', method: :patch

app/views/plans/edit.html.haml
%h1 Editing plan

= render 'form'

= render 'loaned_assignments', assignments: @out_on_loan_assignments, plan: @plan

= link_to 'Show', @plan
\|
= link_to 'Back', plans_path

app/views/plans/index.html.haml
%h1 Listing plans for class #{@classroom.name}

%table.table
  %tr
    %th Date
    %th
    %th
    %th

  - @plans.each do |plan|
    %tr
      %td= plan.updated_at
      %td= link_to 'Show', plan
      %td= link_to 'Edit', edit_plan_path(plan)
      %td= link_to 'Destroy', plan, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Plan', new_classroom_plan_path(@classroom), class: "btn btn-success"

app/views/plans/new.html.haml
%h1 New plan for #{@classroom.name}

= render 'form'

= link_to 'Back to classroom', classroom_path(@classroom)

app/views/plans/show.html.haml
%h2= "Plan: #{@plan.name}"
%time= @plan.created_at

%hr

= link_to 'Edit', edit_plan_path(@plan)
\|
= link_to 'Back to classroom', classroom_path(@plan.classroom)